
#include <iostream>
#include<math.h>

using namespace std;
void three_metrics(int k){
float a1, b1, c1, a2, b2, c2, a3, b3, c3;
float a4, b4, c4, a5, b5, c5, a6, b6, c6;
float a7, b7, c7, a8, b8, c8, a9, b9, c9;
float l, j, n, v;
char t;
 cout <<"BELLLOW ARE THE OPERATION THAT CAN BE BEFORM"<< endl;
 cout<<"------------------------------------------------------------------"<<endl;
 cout<<">>>MULTIPLICATION of METRICES" <<endl;
  cout<<">>>ADDITION  of METRICES" <<endl;
   cout<<">>>SUBTRACTON OF METRICES" <<endl;
    cout<<">>>DIVISION OF METRICES" <<endl;
     cout<<"-----------------------------------------------------------------" <<endl;
      cout<<"CLICK THE FOLLOWING LETTERS TO TO PERFORM THE FOLLOWING OPERATION LISTED" <<endl;
       cout<<">>>MULTIPLICATION ====> M" <<endl; 
        cout<<">>>ADDITION ====> A" <<endl;
         cout<<">>>SUBTRACTION =====> S" <<endl;
          cout<<">>>DIVISION ======> D" <<endl;
           cout<<">>>DETERMINANT====> t" <<endl;
            cout<<">>> INVERSE=======> I" <<endl;
            cin >> t;
             cout<<"--------------------------------------------------------------------" <<endl;
             if(t=='m'){
                 cout<<"the operation should be of the format"<<endl;
              cout<<"(a1 b1  c1)   (a4 b4 c4)"<<endl;
             cout<<"(a2  b2 c2) * (a5 b5 c5)"<<endl;
          cout<<"(a3  b3 c3)   (a6 b6 c6)"<<endl;
        cout<<"ENTER THE VALUE OF a1, b1 and c1 respectively: "<<endl;
         cin >> a1 >>b1 >>c1;
          cout<<"--------------------------------------------------------------------" <<endl;
              cout<<"ENTER THE VALUE OF a2, b2 and c2 respectively: "<<endl;
                 cin >> a2>> b2 >> c2; 
                  cout<<"--------------------------------------------------------------------" <<endl;
                   cout<<"ENTER THE VALUE OF a3, b3 and c3 respectively: "<<endl;
                     cin >> a3>>b3>>c3; 
                     cout<<"--------------------------------------------------------------------" <<endl;
                     cout<<"let move to the nexts metrics "<<endl;
                        cout<<"ENTER THE VALUE OF a4, b4 and c4 respectively: "<<endl;
                          cin >> a4>>b4>>c4; 
                          cout<<"--------------------------------------------------------------------" <<endl;
                        cout<<"ENTER THE VALUE OF a5, b5 and c5 respectively: "<<endl;
                      cin >> a5>>b5>>c5; 
                      cout<<"--------------------------------------------------------------------" <<endl;
                    cout<<"ENTER THE VALUE OF a6, 6 and c6 respectively: "<<endl;
                 cin >> a6>>b6>> c6; 
                  cout<<"--------------------------------------------------------------------" <<endl;
              cout<<"ENTER THE VALUE OF a7, b7 and c7 respectively: "<<endl;
            cin >> a7>>b7>>c7;
            cout<<"--------------------------------------------------------------------" <<endl;
        cout<<"ENTER THE VALUE OF a8, b8 and c8 respectively: "<<endl;
    cin >> a8>>b8>> c8;
      cout<<"--------------------------------------------------------------------" <<endl; 
      cout<<"ENTER THE VALUE OF a9, b9 and c9 respectively: "<<endl;
         cin >> a9>> b9>>c9;
          cout<<"--------------------------------------------------------------------" <<endl;
              a7 = a1*a4 + b1*a5 + c1*a6;
               b7 = a1*b4 + b1*b5 + c1*b6;
                   c7 = a1*c4 + b1*c5 + c1*c6;
                      a8 = a2*a4 + b2*a5 + c2*a6;
                        b8 = a2*b4 + b2*b5 + c2*b6;
                         c8 = a2*a4 + b2*c5 + c2*c6; 
                       a9 = a3*a4 + b3*a5 + c3*a6;
                     b9 = a3*b4 + b3*b5 + c3*b6;
                c9 = a3*c4 + b3*c5 + c3*c6;
               cout<<"THE RESULT IS==>"<<endl;
              cout<<"("<<a7<<" "<<b7<<" "<<c7<<")"<<endl;
            cout<<"("<<a8<<" "<<b8<<" "<<c8<<")"<<endl;
          cout<<"("<<a9<<" "<<b9<<" "<<c9<<")"<<endl;
          }else if(t=='a'){
          cout<<"the operation should be of the format"<<endl;
         cout<<"(a1 b1  c1)   (a4 b4 c4)"<<endl;
         cout<<"(a2  b2 c2) + (a5 b5 c5)"<<endl;
          cout<<"(a3  b3 c3)   (a6 b6 c6)"<<endl;
         cout<<"--------------------------------------------------------------------" <<endl;
           cout<<"ENTER THE VALUE OF a1, b1 and c1 respectively: "<<endl;
         cin >> a1>>b1>>c1;
          cout<<"--------------------------------------------------------------------" <<endl;
              cout<<"ENTER THE VALUE OF a2, b2 and c2 respectively: "<<endl;
                 cin >> a2>>b2>>c2; 
                  cout<<"--------------------------------------------------------------------" <<endl;
                   cout<<"ENTER THE VALUE OF a3, b3 and c3 respectively: "<<endl;
                     cin >> a3>>b3>> c3; 
                     cout<<"let move to the nexts metrics "<<endl;
                         cout<<"ENTER THE VALUE OF a4, b4 and c4 respectively: "<<endl;
                           cin >> a4>>b4>> c4; 
                           cout<<"--------------------------------------------------------------------" <<endl;
                        cout<<"ENTER THE VALUE OF a5, b5 and c5 respectively: "<<endl;
                      cin >> a5>>b5>>c5; 
                       cout<<"--------------------------------------------------------------------" <<endl;
                    cout<<"ENTER THE VALUE OF a6, 6 and c6 respectively: "<<endl;
                 cin >> a6>>b6>>c6; 
                  cout<<"--------------------------------------------------------------------" <<endl;
              cout<<"ENTER THE VALUE OF a7, b7 and c7 respectively: "<<endl;
            cin >> a7>>b7>>c7;
             cout<<"--------------------------------------------------------------------" <<endl;
        cout<<"ENTER THE VALUE OF a8, b8 and c8 respectively: "<<endl;
    cin >> a8>> b8>>c8; 
     cout<<"--------------------------------------------------------------------" <<endl;
      cout<<"ENTER THE VALUE OF a9, b9 and c9 respectively: "<<endl;
         cin >> a9>>b9>> c9;
          cout<<"--------------------------------------------------------------------" <<endl;
              a7 = a1 + a4;
                 b7 = b1 + b4;
                     c7 = c1 + c4;
                        a8 = a2 + a5;
                          b8 = b2 + b5;
                            c8 = c2 + c5;
                          a9 = a3 + a6;
                       b9 = b3 + b6;
                     c9 = c3 + c6;
                     cout<<"--------------------------------------------------------------------" <<endl;
                  cout<<"THE RESULT IS==>"<<endl;
                cout<<"("<<a7<<" "<<b7<<" "<<c7<<")"<<endl;
               cout<<"("<<a8<<" "<<b8<<" "<<c8<<")"<<endl;
              cout<<"("<<a9<<" "<<b9<<" "<<c9<<")"<<endl;
             }else if(t =='s'){
          cout<<"the operation should be of the format"<<endl;
       cout<<"(a1 b1  c1)   (a4 b4 c4)"<<endl;
       cout<<"(a2  b2 c2) - (a5 b5 c5)"<<endl;
      cout<<"(a3  b3 c3)   (a6 b6 c6)"<<endl;
    cout<<"--------------------------------------------------------------------" <<endl;
 cout<<"ENTER THE VALUE OF a1, b1 and c1 respectively: "<<endl;
         cin >> a1>>b1>>c1;
          cout<<"--------------------------------------------------------------------" <<endl;
              cout<<"ENTER THE VALUE OF a2, b2 and c2 respectively: "<<endl;
                 cin >> a2>> b2>>c2; 
                 cout<<"--------------------------------------------------------------------" <<endl;
                   cout<<"ENTER THE VALUE OF a3, b3 and c3 respectively: "<<endl;
                     cin >> a3>>b3>>c3; 
                      cout<<"--------------------------------------------------------------------" <<endl;
                        cout<<"let move to the nexts metrics "<<endl;
                          cout<<"ENTER THE VALUE OF a4, b4 and c4 respectively: "<<endl;
                          cin >> a4>>b4>> c4;
                           cout<<"--------------------------------------------------------------------" <<endl; 
                        cout<<"ENTER THE VALUE OF a5, b5 and c5 respectively: "<<endl;
                      cin >> a5>>b5>>c5; 
                       cout<<"--------------------------------------------------------------------" <<endl;
                    cout<<"ENTER THE VALUE OF a6, 6 and c6 respectively: "<<endl;
                 cin >> a6>> b6>> c6;
                  cout<<"--------------------------------------------------------------------" <<endl; 
              cout<<"ENTER THE VALUE OF a7, b7 and c7 respectively: "<<endl;
            cin >> a7>> b7>>c7;
             cout<<"--------------------------------------------------------------------" <<endl;
        cout<<"ENTER THE VALUE OF a8, b8 and c8 respectively: "<<endl;
    cin >> a8>>b8>>c8; 
     cout<<"--------------------------------------------------------------------" <<endl;
      cout<<"ENTER THE VALUE OF a9, b9 and c9 respectively: "<<endl;
         cin >> a9>> b9>>c9;
           a7= a1 - a4;
                b7 = b1 - b4;
                c7 = c1 - c4;
                  a8 = a2 - a5;
                      b8 = b2 - b5;
                          c8 = c2 - c5;
                            a9 = a3 - a6;
                        b9 = b3 - b6;
                      c9 = c3 - c6;
                      cout<<"--------------------------------------------------------------------" <<endl;
                      cout<<"THE RESULT IS==>"<<endl;
                  cout<<"("<<a7<<" "<<b7<<" "<<c7<<")"<<endl;
               cout<<"("<<a8<<" "<<b8<<" "<<c8<<")"<<endl;
             cout<<"("<<a9<<" "<<b9<<" "<<c9<<")"<<endl;
            }else if(t=='t'){
           cout<<"the operation should be of the format"<<endl;
         cout<<"|a1 b1  c1|"<<endl;
        cout<<"|a2  b2 c2|"<<endl;
          cout<<"|a3  b3 c3|"<<endl;
           cout<<"--------------------------------------------------------------------" <<endl;
            cout<<"ENTER THE VALUE OF a1, b1 and c1 respectively: "<<endl;
              cin >> a1>>b1>>c1;
               cout<<"--------------------------------------------------------------------" <<endl;
                 cout<<"ENTER THE VALUE OF a2, b2 and c2 respectively: "<<endl;
                 cin >> a2>> b2>> c2;
                  cout<<"--------------------------------------------------------------------" <<endl; 
                   cout<<"ENTER THE VALUE OF a3, b3 and c3 respectively: "<<endl;
                     cin >> a3>>b3>>c3;
                     cout<<"--------------------------------------------------------------------" <<endl; 
                       j= a1*c3*b2 - a1*b3*c2; 
                            n= b1*c3*a2 - b1*a3*c2; 
                             v= c1*b3*a2 - c1* a3*b2;
                             l=j-n+v;
                     cout<<"det===>"<<l<<endl;
                 }else if( t=='i'){
                           cout<<"the operation should be of the format"<<endl;
              cout<<"(a1 b1  c1) -|"<<endl;
             cout<<"(a2  b2 c2)"<<endl;
          cout<<"(a3  b3 c3)"<<endl;
          cout<<"--------------------------------------------------------------------" <<endl;
          cout<<"ENTER THE VALUE OF a1, b1 and c1 respectively: "<<endl;
         cin >> a1>>b1>>c1;
          cout<<"--------------------------------------------------------------------" <<endl;
              cout<<"ENTER THE VALUE OF a2, b2 and c2 respectively: "<<endl;
                 cin >> a2>> b2>>c2;
                  cout<<"--------------------------------------------------------------------" <<endl; 
                   cout<<"ENTER THE VALUE OF a3, b3 and c3 respectively: "<<endl;
                     cin >> a3>>b3>>c3;
                     cout<<"--------------------------------------------------------------------" <<endl;
                           
                             j= a1*c3*b2 - a1*b3*c2; 
                           n= b1*c3*a2 - b1*a3*c2; 
                           v= c1*b3*a2 - c1* a3*b2;
                           l=j-n+v;
                           cout <<l<<endl;
                            a4 = c3*b2 - b3*c2;
                                 b4 = c3*a2 - a3*c2;
                                  c4 = a2*b3 - a3*b2;
                               a5 = c3*a1 - b3*c1;
                             b5 = c3*a1 - a3*c1;
                          c5 = b3*a1 - a3*b1;
                       a6 = c2*b1 - b2*c1;
                         b6 = c2*a1 - c1*a2;
                           c6 = b2 *a1 - b1*a2; 
                     
                           cout <<l<<endl;
                             a7=a4/l;
                              b7=-a5/l;
                             c7=a6/l;
                            a8=-b4/l;
                       b8=b5/l;
                     c8=-b6/l;         
                 a9=l/c4;   
                 b9=-c5/l;
                c9=c6/l;
               cout<<"THE INVERSE IS==>"<<endl;
                  cout<<"("<<a7<<" "<<b7<<" "<<c7<<")"<<endl;
                    cout<<"("<<a8<<" "<<b8<<" "<<c8<<")"<<endl;
                      cout<<"("<<a9<<" "<<b9<<" "<<c9<<")"<<endl;
                        }}
                        void two_metrics(int m){
                       float a1, b1, a2, b2 ;
                        float a4, b4, a5, b5;  
                       float a7, b7, a8, b8, l;   
                            char t;
    cout <<"BELLLOW ARE THE OPERATION THAT CAN BE BEFORM"<< endl;
 cout<<"------------------------------------------------------------------"<<endl;
 cout<<">>>MULTIPLICATION of METRICES" <<endl;
  cout<<">>>ADDITION  of METRICES" <<endl;
   cout<<">>>SUBTRACTON OF METRICES" <<endl;
    cout<<">>>DIVISION OF METRICES" <<endl;
     cout<<"-----------------------------------------------------------------" <<endl;
      cout<<"CLICK THE FOLLOWING LETTERS TO TO PERFORM THE FOLLOWING OPERATION LISTED" <<endl;
       cout<<">>>MULTIPLICATION ====> M" <<endl; 
        cout<<">>>ADDITION ====> A" <<endl;
         cout<<">>>SUBTRACTION =====> S" <<endl;
          cout<<">>>DIVISION ======> D" <<endl;
           cout<<">>>DETERMINANT====> t" <<endl;
            cout<<">>> INVERSE=======> I" <<endl;
            cin >> t;
              if(t=='m'){
                  cout<<"the operation should be of the format"<<endl;
                   cout<<"(a1 b1 )   (a4  b4 )"<<endl;
             cout<<"(a2  b2 ) * (a5 b5 )"<<endl;
                cout<<"--------------------------------------------------------------------" <<endl;
          cout<<"ENTER THE VALUE OF a1 and b1   respectively: "<<endl;
         cin >> a1, b1 ;
          cout<<"--------------------------------------------------------------------" <<endl;
              cout<<"ENTER THE VALUE OF a2 and b2  respectively: "<<endl;
                 cin >> a2>>b2;
                  cout<<"--------------------------------------------------------------------" <<endl; 
                   cout<<"ENTER THE VALUE OF a3 and  b3 respectively: "<<endl;
                     cin >> a4>>b4;
                      cout<<"ENTER THE VALUE OF a4 and  b4 respectively: "<<endl;
                     cin >> a5>>b5;
                     cout<<"--------------------------------------------------------------------" <<endl;
                    a7 = a1*a4 + b1*a5;
                    b7 = a1*b4 + b1*b5;
                    a8 = a2*a4 + b2*a5;
                    b8 = a2*b4 + b2*b5;
                     cout<<"THE RESULT IS==>"<<endl;
                  cout<<"("<<a7<<" "<<b7<<" )"<<endl;
                    cout<<"("<<a8<<" "<<b8<<" )"<<endl;
              }else if(t=='a'){
                  cout<<"the operation should be of the format"<<endl;
                           cout<<"(a1 b1 )   (a4  b4 )"<<endl;
             cout<<"(a2  b2 ) + (a5 b5 )"<<endl;
                cout<<"--------------------------------------------------------------------" <<endl;
          cout<<"ENTER THE VALUE OF a1 and b1   respectively: "<<endl;
         cin >> a1>>b1 ;
          cout<<"--------------------------------------------------------------------" <<endl;
              cout<<"ENTER THE VALUE OF a2 and b2  respectively: "<<endl;
                 cin >> a2>>b2;
                  cout<<"--------------------------------------------------------------------" <<endl; 
                   cout<<"ENTER THE VALUE OF a3 and  b3 respectively: "<<endl;
                     cin >> a4>>b4;
                      cout<<"ENTER THE VALUE OF a4 and  b4 respectively: "<<endl;
                     cin >> a5>>b5;
                     cout<<"--------------------------------------------------------------------" <<endl;
                     a7 = a1+a4;
                     b7 = b1+b4;
                     a8= a2+ a5;
                     b8 = b2 +b5;
                       cout<<"THE RESULT IS==>"<<endl;
                  cout<<"("<<a7<<" "<<b7<<" )"<<endl;
                    cout<<"("<<a8<<" "<<b8<<" )"<<endl;
            }else if(t=='s'){
                cout<<"the operation should be of the format"<<endl;
                       cout<<"(a1 b1 )   (a4  b4 )"<<endl;
             cout<<"(a2  b2 ) - (a5 b5 )"<<endl;
                cout<<"--------------------------------------------------------------------" <<endl;
          cout<<"ENTER THE VALUE OF a1 and b1   respectively: "<<endl;
         cin >> a1>>b1 ;
          cout<<"--------------------------------------------------------------------" <<endl;
              cout<<"ENTER THE VALUE OF a2 and b2  respectively: "<<endl;
                 cin >> a2>> b2;
                  cout<<"--------------------------------------------------------------------" <<endl; 
                   cout<<"ENTER THE VALUE OF a3 and  b3 respectively: "<<endl;
                     cin >> a4>>b4;
                      cout<<"ENTER THE VALUE OF a4 and  b4 respectively: "<<endl;
                     cin >> a5>>b5;
                     cout<<"--------------------------------------------------------------------" <<endl;
                     a7 = a1-a4;
                     b7 = b1-b4;
                     a8= a2 - a5;
                     b8 = b2 - b5;
                       cout<<"THE RESULT IS==>"<<endl;
                  cout<<"("<<a7<<" "<<b7<<" )"<<endl;
                    cout<<"("<<a8<<" "<<b8<<" )"<<endl;
                        }else if(t=='t'){
                            cout<<"the operation should be of the format"<<endl;
                            cout<<"|a1 b1 |"<<endl;
                       cout<<"|a2  b2 |"<<endl;
                          cout<<"--------------------------------------------------------------------" <<endl;
          cout<<"ENTER THE VALUE OF a1 and b1   respectively: "<<endl;
         cin >> a1>>b1 ;
          cout<<"--------------------------------------------------------------------" <<endl;
              cout<<"ENTER THE VALUE OF a2 and b2  respectively: "<<endl;
                 cin >> a2>>b2;
                 l = b2*a1 - a2*b1;
                 cout<< "det==>"<<l<<endl;

             }else if(t=='i'){

                     cout<<"the operation should be of the format"<<endl;
                            cout<<"|a1 b1 |-1"<<endl;
                       cout<<"|a2  b2 |"<<endl;
                          cout<<"--------------------------------------------------------------------" <<endl;
          cout<<"ENTER THE VALUE OF a1 and b1   respectively: "<<endl;
         cin >> a1>> b1 ;
          cout<<"--------------------------------------------------------------------" <<endl;
              cout<<"ENTER THE VALUE OF a2 and b2  respectively: "<<endl;
                 cin >> a2>>b2;
                  cout<<"THE INVERSE IS==>"<<endl;
                  cout<<"("<<b2<<" "<<"-"<<b7<<" )"<<endl;
                    cout<<"("<<a8<<" "<<a1<<" )"<<endl;
             }}
               void one_by_three(int o){
             float a1, b1, c1, a2, b2, c2;
           float a3, b3, c3;  
        char t;
    cout <<"BELLLOW ARE THE OPERATION THAT CAN BE BEFORM"<< endl;
 cout<<"------------------------------------------------------------------"<<endl;
 cout<<">>>MULTIPLICATION of METRICES" <<endl;
  cout<<">>>ADDITION  of METRICES" <<endl;
   cout<<">>>SUBTRACTON OF METRICES" <<endl;
   cout <<"-----------------------------------------------------------------------"<<endl;
     cout<<"CLICK THE FOLLOWING LETTERS TO TO PERFORM THE FOLLOWING OPERATION LISTED" <<endl;
    cout<<">>>MULTIPLICATION ====> M" <<endl; 
        cout<<">>>ADDITION ====> A" <<endl;
         cout<<">>>SUBTRACTION =====> S" <<endl;
         cin >> t;
           if(t=='m'){
                  cout<<"the operation should be of the format"<<endl;
                 cout<<"(a1)   (b1)"<<endl;
             cout<<"(a2) * (b2 )"<<endl;
             cout<<"(a3)  (b3 )"<<endl;
                cout<<"--------------------------------------------------------------------" <<endl;
          cout<<"ENTER THE VALUE OF a1, a2 and a3  respectively: "<<endl;
         cin >> a1>>a2>> a3;
          cout<<"--------------------------------------------------------------------" <<endl;
              cout<<"ENTER THE VALUE OF b1,b2 and b3 respectively: "<<endl;
                 cin >> b1, b2, b3;
                 c1 = a1* b1;
                 c2 = a2*b2;
                 c3 = a3*b3;
                  cout<<"THE RESULT IS==>"<<endl;
                    cout<<"("<<c1<<")"<<endl;
                     cout<<"("<<c2<<")"<<endl;
                      cout<<"("<<c3<<")"<<endl;
           }else if(t=='a'){
                  cout<<"the operation should be of the format"<<endl;
                 cout<<"(a1)   (b1)"<<endl;
             cout<<"(a2) + (b2 )"<<endl;
             cout<<"(a3)  (b3 )"<<endl;
                cout<<"--------------------------------------------------------------------" <<endl;
          cout<<"ENTER THE VALUE OF a1, a2 and a3  respectively: "<<endl;
         cin >> a1>> a2>> a3;
          cout<<"--------------------------------------------------------------------" <<endl;
              cout<<"ENTER THE VALUE OF b1,b2   and b3 respectively: "<<endl;
                 cin >> b1, b2, b3;
                 c1 = a1 + b1;
                 c2 = a2 + b2;
                 c3 = a3 + b3;
                  cout<<"THE RESULT IS==>"<<endl;
                    cout<<"("<<c1<<")"<<endl;
                     cout<<"("<<c2<<")"<<endl;
                      cout<<"("<<c3<<")"<<endl;
           }else if(t=='s'){
                  cout<<"the operation should be of the format"<<endl;
                 cout<<"(a1)   (b1)"<<endl;
             cout<<"(a2) - (b2 )"<<endl;
             cout<<"(a3)  (b3 )"<<endl;
                cout<<"--------------------------------------------------------------------" <<endl;
          cout<<"ENTER THE VALUE OF a1, a2 and a3  respectively: "<<endl;
         cin >> a1>>a2>>a3;
          cout<<"--------------------------------------------------------------------" <<endl;
              cout<<"ENTER THE VALUE OF b1,b2 and b3  respectively: "<<endl;
                 cin >> b1>> b2>> b3;
                 c1 = a1 - b1;
                 c2 = a2 - b2;
                 c3 = a3 - b3;
                  cout<<"THE RESULT IS==>"<<endl;
                    cout<<"("<<c1<<")"<<endl;
                     cout<<"("<<c2<<")"<<endl;
                      cout<<"("<<c3<<")"<<endl;
           } }
           void tree_by_two(int z){
                   char t;
             float a1, b1, a2, b2, a3, b3;
             float a4, b4, a5, b5, a6, b6;
             float a7, b7, a8, b8,a9, b9;
              cout <<"BELLLOW ARE THE OPERATION THAT CAN BE BEFORM"<< endl;
 cout<<"------------------------------------------------------------------"<<endl;
 cout<<">>>MULTIPLICATION of METRICES" <<endl;
  cout<<">>>ADDITION  of METRICES" <<endl;
   cout<<">>>SUBTRACTON OF METRICES" <<endl;
   cout <<"-----------------------------------------------------------------------"<<endl;
     cout<<"CLICK THE FOLLOWING LETTERS TO TO PERFORM THE FOLLOWING OPERATION LISTED" <<endl;
    cout<<">>>MULTIPLICATION ====> M" <<endl; 
        cout<<">>>ADDITION ====> A" <<endl;
         cout<<">>>SUBTRACTION =====> S" <<endl;
             cin >> t;
   
     
           if(t=='a'){
                  cout<<"the operation should be of the format"<<endl;
             cout<<"(a1  b1)   (a4 b4)"<<endl;
             cout<<"(a2  b2) +(a5 b5)"<<endl;
             cout<<"(a3  b3)   (a6 b6)"<<endl;
                cout<<"--------------------------------------------------------------------" <<endl;
          cout<<"ENTER THE VALUE OF a1, b1, a2, b2, a3 and b3 respectively: "<<endl;
         cin >> a1>>b1>>a2>>b2>>a3>>b3;
          cout<<"--------------------------------------------------------------------" <<endl;
              cout<<"ENTER THE VALUE OF  a4, b4, a5, b5, a6 and b6  respectively: "<<endl;
              cin >> a4>>b4>>a5>> b5>>a6>>b6;
              a7 = a1 + a4;
              b7 = b1 + b4;
              a8 = a2 + a5;
              b8 = b2 + b5;
              a9 = a3 + a6;
              b9 = b3 + b6;
              cout<<"THE RESULT IS==>"<<endl;
                  cout<<"("<<a7<<" "<<b7<<")"<<endl;
                    cout<<"("<<a8<<" "<<b8<<")"<<endl;
                      cout<<"("<<a9<<" "<<b9<<")"<<endl;
                       }else  if(t== 'm'){
                  cout<<"the operation should be of the format"<<endl;
             cout<<"(a1  b1)  (a4 b4)"<<endl;
             cout<<"(a2  b2) *(a5 b5)"<<endl;
             cout<<"(a3  b3)  (a6 b6)"<<endl;
                cout<<"--------------------------------------------------------------------" <<endl;
          cout<<"ENTER THE VALUE OF a1, b1, a2, b2, a3 and b3 respectively: "<<endl;
         cin >> a1>>b1>> a2>>b2>> a3>>b3;
          cout<<"--------------------------------------------------------------------" <<endl;
              cout<<"ENTER THE VALUE OF  a4, b4, a5, b5, a6 and b6  respectively: "<<endl;
              cin >> a4>> b4>>a5>>b5>>a6>>b6;
              a7 = a1 * a4;
              b7 = b1 * b4;
              a8 = a2 * a5;
              b8 = b2 * b5;
              a9 = a3 * a6;
              b9 = b3 * b6;
              cout<<"THE RESULT IS==>"<<endl;
                  cout<<"("<<a7<<" "<<b7<<")"<<endl;
                    cout<<"("<<a8<<" "<<b8<<")"<<endl;
                      cout<<"("<<a9<<" "<<b9<<")"<<endl; 
                       }else if(t=='s'){
                  cout<<"the operation should be of the format"<<endl;
             cout<<"(a1  b1)  (a4 b4)"<<endl;
             cout<<"(a2  b2)  (a5 b5)"<<endl;
             cout<<"(a3  b3)  (a6 b6)"<<endl;
                cout<<"--------------------------------------------------------------------" <<endl;
          cout<<"ENTER THE VALUE OF a1, b1, a2, b2, a3 and b3 respectively: "<<endl;
         cin >> a1>>b1>>a2>>b2>> a3>>b3;
          cout<<"--------------------------------------------------------------------" <<endl;
              cout<<"ENTER THE VALUE OF  a4, b4, a5, b5, a6 and b6  respectively: "<<endl;
              cin >> a4>>b4>>a5>>b5>>a6>>b6;
              a7 = a1 - a4;
              b7 = b1 - b4;
              a8 = a2 - a5;
              b8 = b2 - b5;
              a9 = a3 - a6;
              b9 = b3 - b6;
                 cout<<"THE RESULT IS==>"<<endl;
                cout<<"("<<a7<<" "<<b7<<")"<<endl;
              cout<<"("<<a8<<" "<<b8<<")"<<endl;
             cout<<"("<<a9<<" "<<b9<<")"<<endl;
           } }
int main(){
    char g, r, u;

    cout<<"welcome to this program you can clck x to exit or clck any buttun on your key baord to continiour: "<<endl;
    cin >> g;
        
while(g !='x'){
 cout<<"---------------------------------------------------------------------------------------------------"<<endl;
 cout<<"the following are the  type of metrics to be perform click the letter to be able to calculate" <<endl;
 cout<<">>> for 3_by_3 metrics click====> R: "<<endl;
  cout<<">>> for 2_by_2 metrics click====> u: "<<endl;
   cout<<">>> for 3_by_1 metrics click====> f: "<<endl;
      cout<<">>> for 3_by_2 metrics click====> z: "<<endl;
  cin >>u;
   cout<<"--------------------------------------------------------------------------------------------------------"<<endl;
   if( u=='r'){
  three_metrics(6);
   }
else if(u=='u'){
two_metrics(8);
}else if (u=='f'){
   one_by_three( 9);
}else if (u=='z'){
 tree_by_two(4);
}else{
  cout <<"INVALID INPUT PLEASE TRY AGIAN"<<endl;
  
}

    cout<<"welcome to this program you can clck x to exit or clck any buttun on your key baord to continiour: "<<endl;
    cin >> g;
}
return 0;
}


                        